# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts {{{

#: kitty has very powerful font management. You can configure
#: individual font faces and even specify special fonts for particular
#: characters.

font_family         FiraCode-Retina
diasable_ligatures  never
font_size           16

# URL Configs
url_style             curly
detect_urls           yes
open_url_with         default
allow_hyperlinks      yes

background_opacity    0.98
macos_titlebar_color #1c8c8e

foreground            #f2f2f2
background            #333333
selection_foreground  #655b53
selection_background  #ebdbb2
url_color             #0087bd

# black
color0   #333333
color8   #88807c

# red
color1   #CC0000
color9   #F15D22

# green
color2   #4E9A06
color10  #73C48F

# yellow
color3   #C4A000
color11  #FFCE51

# blue
color4  #3466A4
color12 #48B9C7

# magenta
color5   #75507b
color13  #AD7FA8

# cyan
color6   #06989a
color14  #34e2e2

# white
color7   #D3D7Cf
color15  #EEEEEC

tab_bar_style powerline
tab_powerline_style round
tab_title_template "{title[:16]}"
active_tab_title_template "🚀 {title} 🌕"
tab_bar_edge top
active_tab_foreground   #000
#00ff9a
active_tab_background #007acc
#1db9e0
active_tab_font_style   bold-italic
inactive_tab_foreground #444
inactive_tab_background #999
inactive_tab_font_style normal

# Mouse
# cursor #ff4d00

# Scrollback
scrollback_lines 99999999

# Remote Control
allow_remote_control enabled

# Fig Kitty Integration: Enabled
watcher ${HOME}/.fig/tools/kitty-integration.py
# End of Fig Kitty Integration

map ctrl+left resize_window narrower
map ctrl+right resize_window wider
map ctrl+up resize_window taller
map ctrl+down resize_window shorter 3
# reset all windows in the tab to default sizes
map ctrl+home resize_window reset
